# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Release and Publish Package to npmjs

on:
  push:
    branches:
      - main

jobs:

  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org/

      - name: Install Npm Dependencies
        run: npm ci

      - name: Increment package version
        run: npm version patch

      - name: Commit version changes
        run: git add package.json && git commit -m "Increment version to v<version_number>"

      - name: Create git release
        run: git tag -a v<version_number> HEAD

      - name: Push git release tag
        run: git push origin v<version_number>

      - name: Build New Release
        run: npm run build-prod

      - name: Publish New Release
        run: cd dist && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
